import React from 'react';
import ScrollAnimation from "react-animate-on-scroll";
import {Link} from "react-router-dom";
import { FiArrowRight, FiCheck } from "react-icons/fi";

const AboutTwo = () => {
    return (
        <div className="rwt-about-area about-style-2 rn-section-gap">
            <div className="container">
                <div className="row row--30 align-items-center justify--center">

                    <div className="col-lg-6 mt_md--30 mt_sm--30 justify--center">
                        <div className="content">
                            <div className="section-title">

                                <ScrollAnimation 
                                animateIn="fadeInUp"
                                animateOut="fadeInOut"
                                animateOnce={true}>
                                    <h1 className="title mt--10">Terms and Conditions</h1>
                                </ScrollAnimation>

                                <ScrollAnimation 
                                animateIn="fadeInUp"
                                animateOut="fadeInOut"
                                animateOnce={true}>
                                    <h4 className="title mt--10">Bubbly Booties is a collection of digital illustrations (NFTs) running on the Ethereum network.</h4>
                                    <h5 className="title mt--50">The Website</h5>
                                    <p>This website is an interface that presents the Bubbly Booties collection of digital illustrations.</p>
                                    <p>The website is provided "as is" without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and non infringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in action of contract, tort or otherwise, arising from, out of or in connection with the website or any third party service.</p>
                                    <h5 className="title mt--50">NFT</h5>
                                    <p>Buying a Bubbly Booties NFT gives you a unique Panda running on the Ethereum network.</p>
                                    <h5 className="title mt--50">Users responsibility</h5>
                                    <p>Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by third party websites before approval.</p>
                                    <p>The Bubbly Booties smart contract runs on the Ethereum network and there is no ability to undo, reverse, or restore any transactions.</p>
                                    <p>It is recommended to only buy a Bubbly Booty from the collection from a reputable website.</p>
                                    <h5 className="title mt--50">Copyright</h5>
                                    <p>The website is offered by Bubbly Booties.</p>
                                    <p>All rights reserved.</p>
                                </ScrollAnimation>
                            </div>
                        </div>
                    </div>
                </div>
            </div>   
        </div>
    )
}

export default AboutTwo;
